"""
Falsification Thresholds - Root Module
======================================

This module re-exports all falsification threshold constants from utils.falsification_thresholds
for backward compatibility and convenience imports.

All threshold constants are defined in utils/falsification_thresholds.py and re-exported here
to maintain compatibility with code that imports from the root level.
"""

# Re-export all constants from utils.falsification_thresholds
from utils.falsification_thresholds import (  # F1 family - Neural signatures; F2 family - Behavioral comparison; F3 family - Intervention effects; F5 family - Evolutionary emergence; F6 family - Liquid network; V12 family - Clinical convergence; Threshold functions; ALPHA configuration; BETA parameters; Depression hyperconnectivity tiers
    ALPHA_EMA,
    ALPHA_FEP,
    ALPHA_SIGMOID,
    BETA_SM,
    BETA_SOMATIC,
    DEPRESSION_HYPERCONNECTIVITY_CONSISTENT,
    DEPRESSION_HYPERCONNECTIVITY_MODERATE,
    DEPRESSION_HYPERCONNECTIVITY_STRONG,
    F1_1_ALPHA,
    F1_1_MIN_ADVANTAGE_PCT,
    F1_1_MIN_COHENS_D,
    F1_5_COHENS_D_MIN,
    F1_5_PAC_INCREASE_MIN,
    F1_5_PAC_MI_MIN,
    F1_5_PERMUTATION_ALPHA,
    F1_6_MIN_LOW_AROUSAL_SLOPE,
    F2_1_ALPHA,
    F2_1_MIN_ADVANTAGE_PCT,
    F2_1_MIN_COHENS_H,
    F2_1_MIN_PP_DIFF,
    F2_2_ALPHA,
    F2_2_MIN_CORR,
    F2_2_MIN_FISHER_Z,
    F2_3_ALPHA,
    F2_3_MIN_BETA,
    F2_3_MIN_R2,
    F2_3_MIN_RT_ADVANTAGE_MS,
    F2_3_MIN_STANDARDIZED_BETA,
    F2_4_ALPHA,
    F2_4_MIN_BETA_INTERACTION,
    F2_4_MIN_CONFIDENCE_EFFECT_PCT,
    F2_5_ALPHA,
    F2_5_MAX_TRIALS,
    F2_5_MIN_ADVANTAGE_PCT,
    F2_5_MIN_HAZARD_RATIO,
    F2_5_MIN_TRIAL_ADVANTAGE,
    F3_1_ALPHA,
    F3_1_MIN_ADVANTAGE_PCT,
    F3_1_MIN_COHENS_D,
    F3_2_ALPHA,
    F3_2_MIN_COHENS_D,
    F3_2_MIN_INTERO_ADVANTAGE_PCT,
    F3_3_ALPHA,
    F3_3_MIN_COHENS_D,
    F3_3_MIN_REDUCTION_PCT,
    F3_4_ALPHA,
    F3_4_MIN_COHENS_D,
    F3_4_MIN_REDUCTION_PCT,
    F3_6_ALPHA,
    F3_6_MAX_TRIALS,
    F3_6_MIN_HAZARD_RATIO,
    F5_1_MIN_ALPHA,
    F5_1_MIN_ALPHA_PAPER_SPEC,
    F5_1_MIN_ALPHA_SIMULATION,
    F5_1_MIN_COHENS_D,
    F5_1_MIN_COHENS_D_PAPER_SPEC,
    F5_1_MIN_COHENS_D_SIMULATION,
    F5_1_MIN_PROPORTION,
    F5_1_MIN_PROPORTION_PAPER_SPEC,
    F5_1_MIN_PROPORTION_SIMULATION,
    F5_2_MIN_CORRELATION,
    F5_2_MIN_PROPORTION,
    F5_3_FALSIFICATION_RATIO,
    F5_3_MIN_COHENS_D,
    F5_3_MIN_GAIN_RATIO,
    F5_3_MIN_PROPORTION,
    F5_4_FALSIFICATION_SEPARATION,
    F5_4_MIN_PEAK_SEPARATION,
    F5_4_MIN_PEAK_SEPARATION_PAPER_SPEC,
    F5_4_MIN_PEAK_SEPARATION_SIMULATION,
    F5_4_MIN_PROPORTION,
    F5_5_MIN_LOADING,
    F5_5_PCA_FALSIFICATION_THRESHOLD,
    F5_5_PCA_MIN_LOADING,
    F5_5_PCA_MIN_VARIANCE,
    F5_6_ALPHA,
    F5_6_MIN_COHENS_D,
    F5_6_MIN_PERFORMANCE_DIFF_PCT,
    F6_1_CLIFFS_DELTA_MIN,
    F6_1_LTCN_MAX_TRANSITION_MS,
    F6_1_MANN_WHITNEY_ALPHA,
    F6_2_LTCN_MIN_WINDOW_MS,
    F6_2_MIN_CURVE_FIT_R2,
    F6_2_MIN_INTEGRATION_RATIO,
    F6_2_MIN_R2,
    F6_2_WILCOXON_ALPHA,
    F6_5_HYSTERESIS_MAX,
    F6_5_HYSTERESIS_MIN,
    F6_6_MIN_PERFORMANCE_GAP,
    V12_1_ALPHA,
    V12_1_MIN_COHENS_D,
    V12_1_MIN_ETA_SQUARED,
    V12_1_MIN_IGNITION_REDUCTION_PCT,
    V12_1_MIN_P3B_REDUCTION_PCT,
    test_f6_1_intrinsic_threshold_behavior,
    test_f6_2_intrinsic_temporal_integration,
    test_f6_3_metabolic_selectivity,
)

__all__ = [
    # ALPHA configuration
    "ALPHA_SIGMOID",
    "ALPHA_EMA",
    "ALPHA_FEP",
    # BETA parameters
    "BETA_SM",
    "BETA_SOMATIC",
    # Depression hyperconnectivity tiers
    "DEPRESSION_HYPERCONNECTIVITY_CONSISTENT",
    "DEPRESSION_HYPERCONNECTIVITY_MODERATE",
    "DEPRESSION_HYPERCONNECTIVITY_STRONG",
    # F1 family
    "F1_1_MIN_ADVANTAGE_PCT",
    "F1_1_MIN_COHENS_D",
    "F1_1_ALPHA",
    "F1_5_PAC_MI_MIN",
    "F1_5_PAC_INCREASE_MIN",
    "F1_5_COHENS_D_MIN",
    "F1_5_PERMUTATION_ALPHA",
    "F1_6_MIN_LOW_AROUSAL_SLOPE",
    # F2 family
    "F2_1_MIN_ADVANTAGE_PCT",
    "F2_1_MIN_PP_DIFF",
    "F2_1_MIN_COHENS_H",
    "F2_1_ALPHA",
    "F2_2_MIN_CORR",
    "F2_2_MIN_FISHER_Z",
    "F2_2_ALPHA",
    "F2_3_MIN_RT_ADVANTAGE_MS",
    "F2_3_MIN_BETA",
    "F2_3_MIN_STANDARDIZED_BETA",
    "F2_3_MIN_R2",
    "F2_3_ALPHA",
    "F2_4_MIN_CONFIDENCE_EFFECT_PCT",
    "F2_4_MIN_BETA_INTERACTION",
    "F2_4_ALPHA",
    "F2_5_MAX_TRIALS",
    "F2_5_MIN_HAZARD_RATIO",
    "F2_5_MIN_TRIAL_ADVANTAGE",
    "F2_5_MIN_ADVANTAGE_PCT",
    "F2_5_ALPHA",
    # F3 family
    "F3_1_MIN_ADVANTAGE_PCT",
    "F3_1_MIN_COHENS_D",
    "F3_1_ALPHA",
    "F3_2_MIN_INTERO_ADVANTAGE_PCT",
    "F3_2_MIN_COHENS_D",
    "F3_2_ALPHA",
    "F3_3_MIN_REDUCTION_PCT",
    "F3_3_MIN_COHENS_D",
    "F3_3_ALPHA",
    "F3_4_MIN_REDUCTION_PCT",
    "F3_4_MIN_COHENS_D",
    "F3_4_ALPHA",
    "F3_6_MAX_TRIALS",
    "F3_6_MIN_HAZARD_RATIO",
    "F3_6_ALPHA",
    # F5 family
    "F5_1_MIN_PROPORTION",
    "F5_1_MIN_PROPORTION_PAPER_SPEC",
    "F5_1_MIN_PROPORTION_SIMULATION",
    "F5_1_MIN_ALPHA",
    "F5_1_MIN_ALPHA_PAPER_SPEC",
    "F5_1_MIN_ALPHA_SIMULATION",
    "F5_1_MIN_COHENS_D",
    "F5_1_MIN_COHENS_D_PAPER_SPEC",
    "F5_1_MIN_COHENS_D_SIMULATION",
    "F5_2_MIN_PROPORTION",
    "F5_2_MIN_CORRELATION",
    "F5_3_MIN_PROPORTION",
    "F5_3_MIN_GAIN_RATIO",
    "F5_3_MIN_COHENS_D",
    "F5_3_FALSIFICATION_RATIO",
    "F5_4_MIN_PROPORTION",
    "F5_4_MIN_PEAK_SEPARATION",
    "F5_4_MIN_PEAK_SEPARATION_PAPER_SPEC",
    "F5_4_MIN_PEAK_SEPARATION_SIMULATION",
    "F5_4_FALSIFICATION_SEPARATION",
    "F5_5_PCA_MIN_VARIANCE",
    "F5_5_PCA_FALSIFICATION_THRESHOLD",
    "F5_5_MIN_LOADING",
    "F5_5_PCA_MIN_LOADING",
    "F5_6_MIN_PERFORMANCE_DIFF_PCT",
    "F5_6_MIN_COHENS_D",
    "F5_6_ALPHA",
    # F6 family
    "F6_1_LTCN_MAX_TRANSITION_MS",
    "F6_1_CLIFFS_DELTA_MIN",
    "F6_1_MANN_WHITNEY_ALPHA",
    "F6_2_LTCN_MIN_WINDOW_MS",
    "F6_2_MIN_INTEGRATION_RATIO",
    "F6_2_MIN_CURVE_FIT_R2",
    "F6_2_MIN_R2",
    "F6_2_WILCOXON_ALPHA",
    "F6_5_HYSTERESIS_MIN",
    "F6_5_HYSTERESIS_MAX",
    "F6_6_MIN_PERFORMANCE_GAP",
    # V12 family
    "V12_1_MIN_P3B_REDUCTION_PCT",
    "V12_1_MIN_IGNITION_REDUCTION_PCT",
    "V12_1_MIN_COHENS_D",
    "V12_1_MIN_ETA_SQUARED",
    "V12_1_ALPHA",
    # Functions
    "test_f6_1_intrinsic_threshold_behavior",
    "test_f6_2_intrinsic_temporal_integration",
    "test_f6_3_metabolic_selectivity",
]
