#!/usr/bin/env python3
"""
Output file pattern detection for APGI validation and falsification protocols.

This module provides utilities to detect and match the actual output file patterns
generated by APGI protocols with the expected patterns used by the validation dashboard.
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Union


class OutputFilePatternMatcher:
    """Matches actual output files with expected protocol patterns."""

    def __init__(self, project_root: Optional[Path] = None):
        """Initialize the pattern matcher.

        Args:
            project_root: Root directory of the APGI project
        """
        self.project_root = project_root or Path(__file__).parent.parent

        self.validation_patterns = {
            "VP_01": [
                "validation_protocol_01.json",
                "vp_01_results.json",
                "vp_01_synthetic_eeg_ml_classification_results.json",
                "synthetic_eeg_ml_classification_results.json",
            ],
            "VP_02": [
                "validation_protocol_02.json",
                "vp_02_results.json",
                "vp_02_behavioral_bayesian_comparison_results.json",
                "behavioral_bayesian_comparison_results.json",
            ],
            "VP_03": [
                "validation_protocol_03.json",
                "vp_03_results.json",
                "vp_03_active_inference_agent_simulations_results.json",
                "active_inference_agent_simulations_results.json",
            ],
            "VP_04": [
                "validation_protocol_04.json",
                "vp_04_results.json",
                "vp_04_phase_transition_epistemic_level2_results.json",
                "phase_transition_epistemic_level2_results.json",
            ],
            "VP_05": [
                "validation_protocol_05.json",
                "vp_05_results.json",
                "vp_05_evolutionary_emergence_results.json",
                "evolutionary_emergence_results.json",
            ],
            "VP_06": [
                "validation_protocol_06.json",
                "vp_06_results.json",
                "vp_06_liquid_network_inductive_bias_results.json",
                "liquid_network_inductive_bias_results.json",
            ],
            "VP_07": [
                "validation_protocol_07.json",
                "vp_07_results.json",
                "vp_07_tms_causal_interventions_results.json",
                "tms_causal_interventions_results.json",
            ],
            "VP_08": [
                "validation_protocol_08.json",
                "vp_08_results.json",
                "vp_08_psychophysical_threshold_estimation_results.json",
                "psychophysical_threshold_estimation_results.json",
            ],
            "VP_09": [
                "validation_protocol_09.json",
                "vp_09_results.json",
                "vp_09_neural_signatures_empirical_priority1_results.json",
                "neural_signatures_empirical_priority1_results.json",
            ],
            "VP_10": [
                "validation_protocol_10.json",
                "vp_10_results.json",
                "vp_10_causal_manipulations_priority2_results.json",
                "causal_manipulations_priority2_results.json",
            ],
            "VP_11": [
                "validation_protocol_11.json",
                "vp_11_results.json",
                "vp_11_mcmc_cultural_neuroscience_priority3_results.json",
                "mcmc_cultural_neuroscience_priority3_results.json",
            ],
            "VP_12": [
                "validation_protocol_12.json",
                "vp_12_results.json",
                "vp_12_clinical_cross_species_convergence_results.json",
                "clinical_cross_species_convergence_results.json",
            ],
            "VP_13": [
                "validation_protocol_13.json",
                "vp_13_results.json",
                "vp_13_epistemic_architecture_results.json",
                "epistemic_architecture_results.json",
            ],
            "VP_14": [
                "validation_protocol_14.json",
                "vp_14_results.json",
                "vp_14_fmri_anticipation_experience_results.json",
                "fmri_anticipation_experience_results.json",
            ],
            "VP_15": [
                "validation_protocol_15.json",
                "vp_15_results.json",
                "vp_15_fmri_anticipation_vmpfc_results.json",
                "fmri_anticipation_vmpfc_results.json",
            ],
            "VP_16": [
                "validation_protocol_16.json",
                "vp_16_results.json",
                "vp_16_metabolic_atp_groundtruth_results.json",
                "metabolic_atp_groundtruth_results.json",
            ],
            "VP_17": [
                "validation_protocol_17.json",
                "vp_17_results.json",
                "vp_17_allen_visual_coding_fatigue_results.json",
                "allen_visual_coding_fatigue_results.json",
            ],
            "VP_18": [
                "validation_protocol_18.json",
                "vp_18_results.json",
                "vp_18_eeg_microstate_gfp_p3b_results.json",
                "eeg_microstate_gfp_p3b_results.json",
            ],
            "VP_19": [
                "validation_protocol_19.json",
                "vp_19_results.json",
                "vp_19_information_erasure_mvpa_results.json",
                "information_erasure_mvpa_results.json",
            ],
            "VP_20": [
                "validation_protocol_20.json",
                "vp_20_results.json",
                "vp_20_empirical_ieeg_results.json",
                "empirical_ieeg_results.json",
            ],
            "VP_21": [
                "validation_protocol_21.json",
                "vp_21_results.json",
                "vp_21_free_energy_prediction_error_results.json",
                "free_energy_prediction_error_results.json",
            ],
        }

        # Falsification protocols - actual patterns used
        self.falsification_patterns = {
            "FP_01": [
                "falsification_protocol_01.json",
                "fp_01_*.json",  # Timestamp pattern: fp_01_YYYYMMDD_HHMMSS.json
                "fp_01_active_inference_results.json",
                "active_inference_results.json",
            ],
            "FP_02": [
                "falsification_protocol_02.json",
                "fp_02_*.json",  # Timestamp pattern
                "fp_02_agent_comparison_convergence_benchmark_results.json",
                "agent_comparison_convergence_benchmark_results.json",
            ],
            "FP_03": [
                "falsification_protocol_03.json",
                "framework_falsification_*.json",  # Timestamp pattern
                "fp_03_framework_level_multiprotocol_results.json",
                "framework_level_multiprotocol_results.json",
            ],
            "FP_04": [
                "falsification_protocol_04.json",
                "fp_04_*.json",
                "fp_04_phase_transition_epistemic_architecture_results.json",
                "phase_transition_epistemic_architecture_results.json",
            ],
            "FP_05": [
                "falsification_protocol_05.json",
                "fp_05_*.json",
                "fp_05_evolutionary_plausibility_results.json",
                "evolutionary_plausibility_results.json",
            ],
            "FP_06": [
                "falsification_protocol_06.json",
                "fp_06_*.json",
                "fp_06_liquid_network_energy_benchmark_results.json",
                "liquid_network_energy_benchmark_results.json",
            ],
            "FP_07": [
                "falsification_protocol_07.json",
                "fp_07_*.json",
                "fp_07_mathematical_consistency_results.json",
                "mathematical_consistency_results.json",
            ],
            "FP_08": [
                "falsification_protocol_08.json",
                "fp_08_*.json",
                "fp_08_parameter_sensitivity_identifiability_results.json",
                "parameter_sensitivity_identifiability_results.json",
            ],
            "FP_09": [
                "falsification_protocol_09.json",
                "fp_09_*.json",
                "fp_09_neural_signatures_p3b_hep_results.json",
                "neural_signatures_p3b_hep_results.json",
            ],
            "FP_10": [
                "falsification_protocol_10.json",
                "fp_10_*.json",
                "fp_10_bayesian_estimation_mcmc_results.json",
                "fp_10_falsification_bayesian_estimation_parameter_recovery_results.json",
                "bayesian_estimation_mcmc_results.json",
            ],
            "FP_11": [
                "falsification_protocol_11.json",
                "fp_11_*.json",
                "fp_11_liquid_network_dynamics_echo_state_results.json",
                "liquid_network_dynamics_echo_state_results.json",
            ],
            "FP_12": [
                "falsification_protocol_12.json",
                "fp_12_*.json",
                "fp_12_cross_species_scaling_results.json",
                "cross_species_scaling_results.json",
            ],
        }

        self.results_dirs = [
            self.project_root / "Falsification/results",
            self.project_root / "validation_results",
            self.project_root / "data_repository/processed",
        ]

    def find_protocol_output_files(self, protocol_id: str) -> List[Path]:
        """Find all output files for a specific protocol.

        Args:
            protocol_id: Protocol identifier (e.g., "VP_01", "FP_01")

        Returns:
            List of found output file paths
        """
        found_files: list[Path] = []

        # Get the appropriate pattern list
        if protocol_id.startswith("VP_"):
            patterns = self.validation_patterns.get(protocol_id, [])
        elif protocol_id.startswith("FP_"):
            patterns = self.falsification_patterns.get(protocol_id, [])
        else:
            return found_files

        # Search in all results directories
        for results_dir in self.results_dirs:
            if not results_dir.exists():
                continue

            for pattern in patterns:
                # Handle glob patterns with wildcards
                if "*" in pattern:
                    # Use glob for wildcard patterns
                    matching_files = list(results_dir.glob(pattern))
                    found_files.extend(matching_files)
                else:
                    # Check for exact filename match
                    exact_file = results_dir / pattern
                    if exact_file.exists():
                        found_files.append(exact_file)

        # Also search in project root
        for pattern in patterns:
            if "*" in pattern:
                matching_files = list(self.project_root.glob(pattern))
                found_files.extend(matching_files)
            else:
                exact_file = self.project_root / pattern
                if exact_file.exists():
                    found_files.append(exact_file)

        # Remove duplicates and sort by modification time (newest first)
        unique_files = []
        seen = set()
        for file_path in sorted(found_files, key=lambda p: p.stat().st_mtime, reverse=True):
            if file_path not in seen:
                unique_files.append(file_path)
                seen.add(file_path)

        return unique_files

    def get_latest_output_file(self, protocol_id: str) -> Optional[Path]:
        """Get the most recent output file for a protocol.

        Args:
            protocol_id: Protocol identifier

        Returns:
            Path to the most recent output file, or None if none found
        """
        files = self.find_protocol_output_files(protocol_id)
        return files[0] if files else None

    def load_protocol_results(self, protocol_id: str) -> Optional[Dict]:
        """Load and parse the most recent results for a protocol.

        Args:
            protocol_id: Protocol identifier

        Returns:
            Parsed results dictionary, or None if no file found or invalid JSON
        """
        latest_file = self.get_latest_output_file(protocol_id)
        if not latest_file:
            return None

        try:
            with open(latest_file, "r", encoding="utf-8") as f:
                return json.load(f)
        except (json.JSONDecodeError, IOError, UnicodeDecodeError) as e:
            print(f"Error loading results from {latest_file}: {e}")
            return None

    def validate_protocol_output(self, protocol_id: str) -> Dict[str, Union[str, bool, int, None]]:
        """Validate that a protocol has output files and valid JSON structure.

        Args:
            protocol_id: Protocol identifier

        Returns:
            Dictionary with validation status
        """
        files = self.find_protocol_output_files(protocol_id)

        validation_result: Dict[str, Union[str, bool, int]] = {
            "has_files": len(files) > 0,
            "has_valid_json": False,
            "file_count": len(files),
            "latest_file": str(files[0]) if files else None,
        }

        # Check if any file has valid JSON
        for file_path in files:
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    if isinstance(data, dict) and data:
                        validation_result["has_valid_json"] = True  # type: ignore[assignment]  # type: ignore[assignment]
                        break
            except (json.JSONDecodeError, IOError, UnicodeDecodeError):
                continue

        return validation_result

    def get_all_protocol_status(self) -> Dict[str, Dict[str, Union[str, bool, int]]]:
        """Get status for all protocols.

        Returns:
            Dictionary mapping protocol IDs to their validation status
        """
        all_protocols = {}

        # Check validation protocols
        for vp_id in self.validation_patterns.keys():
            all_protocols[vp_id] = self.validate_protocol_output(vp_id)

        # Check falsification protocols
        for fp_id in self.falsification_patterns.keys():
            all_protocols[fp_id] = self.validate_protocol_output(fp_id)

        return all_protocols

    def update_validation_history(self):
        """Update the validation history with current protocol status."""
        all_status = self.get_all_protocol_status()

        # Load existing history
        history_file = self.project_root / "data_repository/dashboard_data/validation_history.json"
        history = []

        if history_file.exists():
            try:
                with open(history_file, "r", encoding="utf-8") as f:
                    history = json.load(f)
            except (json.JSONDecodeError, IOError):
                history = []

        # Add current status entries
        current_time = datetime.now().isoformat()

        for protocol_id, status in all_status.items():
            if status["has_files"] and status["has_valid_json"]:
                # Determine protocol type and number
                if protocol_id.startswith("VP_"):
                    protocol_num = int(protocol_id.split("_")[1])
                    protocol_type = "validation"
                elif protocol_id.startswith("FP_"):
                    protocol_num = int(protocol_id.split("_")[1])
                    protocol_type = "falsification"
                else:
                    continue

                # Load the actual results to get more details
                results = self.load_protocol_results(protocol_id)

                # Create history entry
                history_entry = {
                    "timestamp": current_time,
                    "protocol_number": protocol_num,
                    "protocol_name": f"{protocol_type.title()} Protocol {protocol_num}",
                    "status": ("pass" if self._count_passed_criteria(results) > 0 else "fail"),
                    "execution_time": results.get("execution_time", 0.0),
                    "tests_passed": self._count_passed_criteria(results),
                    "tests_failed": self._count_failed_criteria(results),
                    "error_message": None,
                    "metadata": {
                        "protocol_type": protocol_type,
                        "file_pattern": status.get("latest_file", ""),
                        "protocol_id": protocol_id,
                    },
                }

                history.append(history_entry)

        # Save updated history
        history_file.parent.mkdir(parents=True, exist_ok=True)
        with open(history_file, "w", encoding="utf-8") as f:
            json.dump(history, f, indent=2)

    def _count_passed_criteria(self, results: Dict) -> int:
        """Count passed criteria from results dictionary."""
        if not isinstance(results, dict):
            return 0

        passed_count = 0

        # Handle different result structures
        if "summary" in results:
            summary = results["summary"]
            if isinstance(summary, dict):
                passed_count = summary.get("passed", 0)

        # Count individual criteria
        for key, value in results.items():
            if key.startswith(("F", "P", "V")) and isinstance(value, dict):
                if value.get("passed", False):
                    passed_count += 1

        return passed_count

    def _count_failed_criteria(self, results: Dict) -> int:
        """Count failed criteria from results dictionary."""
        if not isinstance(results, dict):
            return 0

        failed_count = 0

        # Handle different result structures
        if "summary" in results:
            summary = results["summary"]
            if isinstance(summary, dict):
                failed_count = summary.get("failed", 0)

        # Count individual criteria
        for key, value in results.items():
            if key.startswith(("F", "P", "V")) and isinstance(value, dict):
                if not value.get("passed", True):
                    failed_count += 1

        return failed_count


# Convenience function for getting protocol status
def get_protocol_status(
    project_root: Optional[Path] = None,
) -> Dict[str, Dict[str, Union[str, bool, int]]]:
    """Get status for all protocols.

    Args:
        project_root: Root directory of the APGI project

    Returns:
        Dictionary mapping protocol IDs to their validation status
    """
    matcher = OutputFilePatternMatcher(project_root)
    return matcher.get_all_protocol_status()


def main():
    """Test the pattern matcher."""
    matcher = OutputFilePatternMatcher()

    print("APGI Protocol Output File Pattern Matcher")
    print("=" * 50)

    # Check all protocols
    all_status = matcher.get_all_protocol_status()

    print("\nProtocol Status:")
    print("-" * 40)

    for protocol_id, status in sorted(all_status.items()):
        has_files = status["has_files"]
        has_json = status["has_valid_json"]
        file_count = status["file_count"]

        status_icon = "✅" if has_files and has_json else "❌"
        print(f"{status_icon} {protocol_id}: {file_count} files, JSON valid: {has_json}")

        if status["latest_file"]:
            print(f"    Latest: {Path(status['latest_file']).name}")

    # Update validation history
    print("\nUpdating validation history...")
    matcher.update_validation_history()
    print("✅ Validation history updated")


if __name__ == "__main__":
    main()
